"""Add priorities to attendances.

Revision ID: 04b502b52aa5
Revises: d726d6b9eaf6
Create Date: 2023-03-15 17:47:00.215494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b502b52aa5'
down_revision = 'd726d6b9eaf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('priority', sa.Integer(), nullable=True))
    op.execute('UPDATE attendances SET priority = 50;')
    op.alter_column('attendances', 'priority', nullable=False)
    op.drop_column('events', 'priority')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('priority', sa.Integer(), nullable=True))
    op.drop_column('attendances', 'priority')
    # ### end Alembic commands ###
