"""Make gcal_sync_log calendar_id nullable.

Revision ID: 076aab96b53b
Revises: b843dc44e52d
Create Date: 2022-11-28 13:48:33.281176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '076aab96b53b'
down_revision = 'b843dc44e52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gcal_sync_log', 'calendar_id', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gcal_sync_log', 'calendar_id', nullable=False)
    # ### end Alembic commands ###
