"""Add state to draft events.

Revision ID: 097ab5e9cfbc
Revises: 5cb01cf29ef3
Create Date: 2022-06-27 13:49:28.833014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097ab5e9cfbc'
down_revision = '5cb01cf29ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_events', sa.Column('state', sa.Integer(), nullable=True))
    op.execute('UPDATE draft_events SET state = 1 WHERE deleting = false') # sync
    op.execute('UPDATE draft_events SET state = 2 WHERE deleting = true') # awaiting_delete
    op.alter_column('draft_events', 'state', nullable=False)
    op.drop_column('draft_events', 'deleting')
    op.alter_column('events', 'deleting', new_column_name='hidden')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'hidden', new_column_name='deleting')
    op.add_column('draft_events', sa.Column('deleting', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.execute('UPDATE draft_events SET deleting = false')
    op.execute('UPDATE draft_events SET deleting = true WHERE state = 2') # awaiting_delete
    op.execute('UPDATE draft_events SET deleting = true WHERE state = 4') # finalizing
    op.execute('UPDATE draft_events SET deleting = true WHERE state = 5') # finalized_awaiting_delete
    op.execute('DELETE from draft_events WHERE state = 3 OR state = 6 OR state = 7') # done, awaiting_final, finalized
    op.alter_column('draft_events', 'deleting', nullable=False)
    op.drop_column('draft_events', 'state')
    # ### end Alembic commands ###
