"""Add cols for gcal calendar list notifications.

Revision ID: 101334eef2f4
Revises: f5956d420688
Create Date: 2022-12-08 11:14:05.986315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101334eef2f4'
down_revision = 'f5956d420688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kalendar_delete_count', sa.Integer(), nullable=True))
    op.execute('UPDATE users SET kalendar_delete_count = 0;')
    op.alter_column('users', 'kalendar_delete_count', nullable=False)
    op.add_column('users', sa.Column('gcal_resource_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('gcal_channel_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('gcal_channel_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('gcal_watch_error_count', sa.Integer(), nullable=True))
    op.execute('UPDATE users SET gcal_watch_error_count = 0;')
    op.alter_column('users', 'gcal_watch_error_count', nullable=False)
    op.add_column('users', sa.Column('gcal_watch_last_error', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['gcal_channel_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'gcal_watch_last_error')
    op.drop_column('users', 'gcal_watch_error_count')
    op.drop_column('users', 'gcal_channel_expires_at')
    op.drop_column('users', 'gcal_channel_id')
    op.drop_column('users', 'gcal_resource_id')
    op.drop_column('users', 'kalendar_delete_count')
    # ### end Alembic commands ###
