"""Add send_new_meeting_notifications to users.

Revision ID: 169595e9fb9f
Revises: 101334eef2f4
Create Date: 2022-12-20 16:19:44.853467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '169595e9fb9f'
down_revision = '101334eef2f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('send_new_meeting_notifications', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET send_new_meeting_notifications = true;')
    op.alter_column('users', 'send_new_meeting_notifications', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'send_new_meeting_notifications')
    # ### end Alembic commands ###
