"""Add tzname to users.

Revision ID: 186d8774b7a2
Revises: 0527979398f3
Create Date: 2022-07-13 14:52:38.585856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186d8774b7a2'
down_revision = '0527979398f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tzname', sa.String(length=48), nullable=True))
    op.execute("UPDATE users SET tzname = 'America/Los_Angeles'")
    op.execute("UPDATE users SET tzname = 'Europe/London' WHERE (preferences::json->'offset')::text::int = -1")
    op.execute("UPDATE users SET tzname = 'Africa/Johannesburg' WHERE (preferences::json->'offset')::text::int = -2")
    op.execute("UPDATE users SET tzname = 'America/New_York' WHERE (preferences::json->'offset')::text::int = 4")
    op.alter_column('users', 'tzname', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tzname')
    # ### end Alembic commands ###
