"""Add gcal sync count to events.

Revision ID: 252a90a4b625
Revises: 9f4b418c498f
Create Date: 2022-08-26 19:43:32.557226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252a90a4b625'
down_revision = '9f4b418c498f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('gcal_sync_count', sa.Integer(), nullable=True))
    op.execute('UPDATE events SET gcal_sync_count = 0;')
    op.alter_column('events', 'gcal_sync_count', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'gcal_sync_count')
    # ### end Alembic commands ###
