"""Add per-attendee gcal entry cols.

Revision ID: 2babe41ca01a
Revises: 04b502b52aa5
Create Date: 2023-03-21 14:42:25.611069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2babe41ca01a'
down_revision = '04b502b52aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('gcal_uid', sa.String(length=64), nullable=True))
    op.add_column('attendances', sa.Column('gcal_hash', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'attendances', ['gcal_uid'])
    op.add_column('events', sa.Column('gcal_sync_version', sa.Integer(), nullable=True))
    op.execute('UPDATE events SET gcal_sync_version = 0 WHERE use_new_sync = false;')
    op.execute('UPDATE events SET gcal_sync_version = 1 WHERE use_new_sync = true;')
    op.alter_column('events', 'gcal_sync_version', nullable=False)
    op.drop_column('events', 'use_new_sync')

    op.add_column('attendances', sa.Column('gcal_create_count', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('gcal_update_count', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('gcal_delete_count', sa.Integer(), nullable=True))
    op.execute('UPDATE attendances SET gcal_create_count = 0, gcal_update_count = 0, gcal_delete_count = 0;')
    op.alter_column('attendances', 'gcal_create_count', nullable=False)
    op.alter_column('attendances', 'gcal_update_count', nullable=False)
    op.alter_column('attendances', 'gcal_delete_count', nullable=False)

    op.add_column('attendances', sa.Column('gcal_calendar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendances', 'calendars', ['gcal_calendar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_column('attendances', 'gcal_calendar_id')

    op.drop_column('attendances', 'gcal_delete_count')
    op.drop_column('attendances', 'gcal_update_count')
    op.drop_column('attendances', 'gcal_create_count')

    op.add_column('events', sa.Column('use_new_sync', sa.Boolean(), nullable=True))
    op.execute('UPDATE events SET use_new_sync = false WHERE gcal_sync_version = 0;')
    op.execute('UPDATE events SET use_new_sync = true WHERE gcal_sync_version = 1;')
    op.alter_column('events', 'use_new_sync', nullable=False)
    op.drop_column('events', 'gcal_sync_version')
    op.drop_constraint(None, 'attendances', type_='unique')
    op.drop_column('attendances', 'gcal_hash')
    op.drop_column('attendances', 'gcal_uid')
    # ### end Alembic commands ###
