"""Add availability migration cols.

Revision ID: 2ca505d0d67a
Revises: f17aa439e959
Create Date: 2023-06-13 13:53:14.656189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca505d0d67a'
down_revision = 'f17aa439e959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendars', sa.Column('migration_strategy', sa.Integer(), nullable=True))
    op.add_column('calendars', sa.Column('migration_state', sa.Integer(), nullable=True))
    op.execute('UPDATE calendars SET migration_strategy = 0, migration_state = 0;')
    op.alter_column('calendars', 'migration_strategy', nullable=False)
    op.alter_column('calendars', 'migration_state', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendars', 'migration_state')
    op.drop_column('calendars', 'migration_strategy')
    # ### end Alembic commands ###
