"""Add index to support fixed event queries.

Revision ID: 3901456fb707
Revises: d268bdc628c8
Create Date: 2022-08-24 20:27:32.919031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3901456fb707'
down_revision = 'd268bdc628c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_fixed_events_calendar_id_start_dt_end_dt', 'fixed_events', ['calendar_id', 'start_dt', 'end_dt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fixed_events_calendar_id_start_dt_end_dt', table_name='fixed_events')
    # ### end Alembic commands ###
