"""Add error log.

Revision ID: 40234adf1775
Revises: cb7d34a847a3
Create Date: 2022-06-08 09:19:31.710404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40234adf1775'
down_revision = 'cb7d34a847a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('jsondata', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('error_log')
    # ### end Alembic commands ###
