"""Add priority to events.

Revision ID: 4c73dbc55962
Revises: 171a4f5c0c2f
Create Date: 2022-04-15 13:26:28.066705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c73dbc55962'
down_revision = '171a4f5c0c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixed_events', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixed_events', 'priority')
    # ### end Alembic commands ###
