"""Add series.

Revision ID: 59baaf3b3f2c
Revises: b73c8a249693
Create Date: 2022-05-09 15:41:50.840012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59baaf3b3f2c'
down_revision = 'b73c8a249693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('series_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'series', ['series_id'], ['id'])
    op.drop_column('events', 'is_recurring')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_recurring', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'series_id')
    op.drop_table('series')
    # ### end Alembic commands ###
