"""Add extra cols for gcal sync config.

Revision ID: 5f0798cb9385
Revises: 2babe41ca01a
Create Date: 2023-04-20 16:48:54.658466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0798cb9385'
down_revision = '2babe41ca01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gcal_sync_2_add_self', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET gcal_sync_2_add_self = true;')
    op.alter_column('users', 'gcal_sync_2_add_self', nullable=False)
    op.add_column('users', sa.Column('gcal_sync_enabled', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET gcal_sync_enabled = true;')
    op.alter_column('users', 'gcal_sync_enabled', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gcal_sync_enabled')
    op.drop_column('users', 'gcal_sync_2_add_self')
    # ### end Alembic commands ###
