"""Add sign_up_steps_json to emails.

Revision ID: 64cc31e5afba
Revises: 169595e9fb9f
Create Date: 2023-02-02 17:16:42.365223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cc31e5afba'
down_revision = '169595e9fb9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('sign_up_steps_json', sa.Text(), nullable=True))
    op.execute("UPDATE emails SET sign_up_steps_json = '[]';")
    op.alter_column('emails', 'sign_up_steps_json', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'sign_up_steps_json')
    # ### end Alembic commands ###
