"""Add lm_cache / poems flag.

Revision ID: 66b7d655bc94
Revises: 71116de8bbe1
Create Date: 2023-04-26 16:56:18.897886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b7d655bc94'
down_revision = '71116de8bbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lm_cache',
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.add_column('users', sa.Column('poems', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET poems = true;')
    op.alter_column('users', 'poems', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'poems')
    op.drop_table('lm_cache')
    # ### end Alembic commands ###
