"""Add local window cols to events.

Revision ID: 66e2cd385e1c
Revises: 86cd24dea9df
Create Date: 2022-08-03 14:07:57.005233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e2cd385e1c'
down_revision = '86cd24dea9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('tzname', sa.String(length=48), nullable=True))
    op.add_column('events', sa.Column('window_start_local', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('window_end_local', sa.DateTime(), nullable=True))
    op.execute("UPDATE events SET tzname = 'UTC', window_start_local = window_start, window_end_local = window_end")
    op.alter_column('events', 'tzname', nullable=False)
    op.alter_column('events', 'window_start_local', nullable=False)
    op.alter_column('events', 'window_end_local', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'window_end_local')
    op.drop_column('events', 'window_start_local')
    op.drop_column('events', 'tzname')
    # ### end Alembic commands ###
