"""Add bitmaps.

Revision ID: 71116de8bbe1
Revises: b47cd5620728
Create Date: 2023-04-24 14:28:31.013662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71116de8bbe1'
down_revision = 'b47cd5620728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('data', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bitmaps')
    # ### end Alembic commands ###
