"""Add gcal_conf_data to events.

Revision ID: 73c7681f8e04
Revises: c48a56e2cf58
Create Date: 2022-11-07 15:02:43.160280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c7681f8e04'
down_revision = 'c48a56e2cf58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('gcal_conf_data_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'gcal_conf_data_json')
    # ### end Alembic commands ###
