"""Change tracking for more incremental solving.

Revision ID: 7afc1794b768
Revises: d007d45615a2
Create Date: 2022-06-21 21:19:41.911912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7afc1794b768'
down_revision = 'd007d45615a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('users', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('conflict', sa.Boolean(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('fixed_event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['fixed_event_id'], ['fixed_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('fixed_event_id')
    )
    op.add_column('events', sa.Column('dirty', sa.Boolean(), nullable=True))
    op.execute('UPDATE events SET dirty = false')
    op.alter_column('events', 'dirty', nullable=False)
    op.add_column('fixed_events', sa.Column('dirty', sa.Boolean(), nullable=True))
    op.execute('UPDATE fixed_events SET dirty = false')
    op.alter_column('fixed_events', 'dirty', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixed_events', 'dirty')
    op.drop_column('events', 'dirty')
    op.drop_table('changes')
    # ### end Alembic commands ###
