"""Add use_new_sync to events.

Revision ID: 86cd24dea9df
Revises: 186d8774b7a2
Create Date: 2022-07-21 15:26:14.004162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86cd24dea9df'
down_revision = '186d8774b7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('use_new_sync', sa.Boolean(), nullable=True))
    op.execute('UPDATE events SET use_new_sync = false')
    op.alter_column('events', 'use_new_sync', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'use_new_sync')
    # ### end Alembic commands ###
