"""Add setup cols to users.

Revision ID: 9697623bdb65
Revises: 66e2cd385e1c
Create Date: 2022-07-26 14:12:54.563990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9697623bdb65'
down_revision = '66e2cd385e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('setup_json', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('setup_step', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('setup_complete', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET setup_complete = true')
    op.alter_column('users', 'setup_complete', nullable=False)
    op.add_column('users', sa.Column('kalendar_gcal_id', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kalendar_gcal_id')
    op.drop_column('users', 'setup_complete')
    op.drop_column('users', 'setup_step')
    op.drop_column('users', 'setup_json')
    # ### end Alembic commands ###
