"""Add gcal_event_data_hash to events.

Revision ID: 9f4b418c498f
Revises: b33bf8958582
Create Date: 2022-08-26 09:18:54.827006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4b418c498f'
down_revision = 'b33bf8958582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('gcal_event_data_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'gcal_event_data_hash')
    # ### end Alembic commands ###
