"""Add gcal quotas.

Revision ID: a0065c4c2d3b
Revises: fc221bfe41a7
Create Date: 2022-09-23 18:51:55.727061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0065c4c2d3b'
down_revision = 'fc221bfe41a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('gcal_create_count', sa.Integer(), nullable=True))
    op.execute('UPDATE events SET gcal_create_count = 0;')
    op.alter_column('events', 'gcal_create_count', nullable=False)

    op.add_column('events', sa.Column('gcal_update_count', sa.Integer(), nullable=True))
    op.execute('UPDATE events SET gcal_update_count = 0;')
    op.alter_column('events', 'gcal_update_count', nullable=False)

    op.add_column('events', sa.Column('gcal_delete_count', sa.Integer(), nullable=True))
    op.execute('UPDATE events SET gcal_delete_count = 0;')
    op.alter_column('events', 'gcal_delete_count', nullable=False)

    op.add_column('users', sa.Column('gcal_quota', sa.Integer(), nullable=True))
    op.execute('UPDATE users SET gcal_quota = 1000;')
    op.alter_column('users', 'gcal_quota', nullable=False)

    op.add_column('users', sa.Column('gcal_quota_updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE users SET gcal_quota_updated_at = now() at time zone('utc');")
    op.alter_column('users', 'gcal_quota_updated_at', nullable=False)

    op.add_column('users', sa.Column('gcal_quota_period', sa.Interval(), nullable=True))
    op.execute("UPDATE users SET gcal_quota_period = '15 minutes'::interval;")
    op.alter_column('users', 'gcal_quota_period', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gcal_quota_period')
    op.drop_column('users', 'gcal_quota_updated_at')
    op.drop_column('users', 'gcal_quota')
    op.drop_column('events', 'gcal_delete_count')
    op.drop_column('events', 'gcal_update_count')
    op.drop_column('events', 'gcal_create_count')
    # ### end Alembic commands ###
