"""Replace bitmaps with availability_events.

Revision ID: a95e71f5c27b
Revises: 66b7d655bc94
Create Date: 2023-05-05 15:38:13.978426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a95e71f5c27b'
down_revision = '66b7d655bc94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tzname', sa.String(length=48), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('recur_end_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_availability_events_user_id_recur_end_at_start_at', 'availability_events', ['user_id', 'recur_end_at', 'start_at'], unique=False)
    op.drop_table('bitmaps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitmaps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='bitmaps_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bitmaps_pkey'),
    sa.UniqueConstraint('user_id', 'date', name='bitmaps_user_id_date_key')
    )
    op.drop_index('ix_availability_events_user_id_recur_end_at_start_at', table_name='availability_events')
    op.drop_table('availability_events')
    # ### end Alembic commands ###
