"""Add calendar_id to events.

Revision ID: af435a3f3c06
Revises: 076aab96b53b
Create Date: 2022-11-28 14:17:29.245648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af435a3f3c06'
down_revision = '076aab96b53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('calendar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'calendars', ['calendar_id'], ['id'])
    op.execute("UPDATE events SET calendar_id = active_calendar_id FROM users "
               "WHERE events.creator_id = users.id and not events.uid is null;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'calendar_id')
    # ### end Alembic commands ###
