"""Clean-up some used cols.

Revision ID: b47cd5620728
Revises: 5f0798cb9385
Create Date: 2023-04-21 15:33:57.925295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b47cd5620728'
down_revision = '5f0798cb9385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', '_attendees')
    op.drop_column('events', '_invitees')
    op.drop_column('events', '_optionalattendees')
    op.drop_column('events', '_optionalinvitees')
    op.drop_column('events', 'gcal_sync_count')
    op.drop_column('events', 'gcal_event_data_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('gcal_event_data_hash', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('gcal_sync_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('_optionalinvitees', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('_optionalattendees', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('_invitees', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('_attendees', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
