"""Add gcal_sync_log.

Revision ID: b843dc44e52d
Revises: 73c7681f8e04
Create Date: 2022-11-24 11:57:39.240870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b843dc44e52d'
down_revision = '73c7681f8e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gcal_sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('full', sa.Boolean(), nullable=False),
    sa.Column('elapsed', sa.Integer(), nullable=False),
    sa.Column('num_items', sa.Integer(), nullable=False),
    sa.Column('num_changes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gcal_sync_log_calendar_id'), 'gcal_sync_log', ['calendar_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gcal_sync_log_calendar_id'), table_name='gcal_sync_log')
    op.drop_table('gcal_sync_log')
    # ### end Alembic commands ###
