"""Add gcal_sync_state_json and location to events.

Revision ID: c48a56e2cf58
Revises: a0065c4c2d3b
Create Date: 2022-10-12 10:05:29.865661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48a56e2cf58'
down_revision = 'a0065c4c2d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('gcal_sync_state_json', sa.Text(), nullable=True))
    op.execute("UPDATE events SET gcal_sync_state_json = '{}';")
    op.alter_column('events', 'gcal_sync_state_json', nullable=False)
    op.add_column('events', sa.Column('location', sa.String(length=1024), nullable=True))
    op.execute("UPDATE events SET location = '';")
    op.alter_column('events', 'location', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'gcal_sync_state_json')
    op.drop_column('events', 'location')
    # ### end Alembic commands ###
