"""Add event invitees.

Revision ID: cb7d34a847a3
Revises: 59baaf3b3f2c
Create Date: 2022-06-02 15:24:48.405764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb7d34a847a3'
down_revision = '59baaf3b3f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('pending', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('invitees', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('events', sa.Column('optionalinvitees', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.execute("UPDATE events SET pending = false, invitees = '{}', optionalinvitees = '{}'")
    op.alter_column('events', 'pending', nullable=False)
    op.alter_column('events', 'invitees', nullable=False)
    op.alter_column('events', 'optionalinvitees', nullable=False)
    op.add_column('invites', sa.Column('uid', sa.String(length=32), nullable=True))
    op.add_column('invites', sa.Column('declined', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.execute("UPDATE invites SET uid = id, declined = '{}'")
    op.alter_column('invites', 'uid', nullable=False)
    op.alter_column('invites', 'declined', nullable=False)
    op.create_unique_constraint(None, 'invites', ['uid'])
    op.drop_column('invites', 'sent')
    op.drop_column('invites', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('invites', sa.Column('sent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invites', type_='unique')
    op.drop_column('invites', 'declined')
    op.drop_column('invites', 'uid')
    op.drop_column('events', 'optionalinvitees')
    op.drop_column('events', 'invitees')
    op.drop_column('events', 'pending')
    # ### end Alembic commands ###
