"""Add state to events.

Revision ID: d007d45615a2
Revises: 40234adf1775
Create Date: 2022-06-09 11:09:04.496423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd007d45615a2'
down_revision = '40234adf1775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('state', sa.Integer(), nullable=True))
    op.execute('UPDATE events SET state = 0 WHERE pending = false AND is_finalized = false AND draft_start IS NULL')
    op.execute('UPDATE events SET state = 1 WHERE pending = true and is_finalized = false')
    op.execute('UPDATE events SET state = 2 WHERE pending = false AND is_finalized = false AND draft_start IS NOT NULL')
    op.execute('UPDATE events SET state = 3 WHERE is_finalized = true')
    op.alter_column('events', 'state', nullable=False)
    op.drop_column('events', 'pending')
    op.drop_column('events', 'is_finalized')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_finalized', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('pending', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.execute('UPDATE events SET pending = false, is_finalized = false WHERE state = 0')
    op.execute('UPDATE events SET pending = true, is_finalized = false WHERE state = 1')
    op.execute('UPDATE events SET pending = false, is_finalized = false WHERE state = 2')
    op.execute('UPDATE events SET pending = false, is_finalized = true WHERE state = 3')
    op.alter_column('events', 'pending', nullable=False)
    op.drop_column('events', 'state')
    # ### end Alembic commands ###
