"""Add watch error count to calendars.

Revision ID: d268bdc628c8
Revises: 252a90a4b625
Create Date: 2022-08-29 09:49:00.941255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd268bdc628c8'
down_revision = '252a90a4b625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendars', sa.Column('gcal_watch_error_count', sa.Integer(), nullable=True))
    op.execute('UPDATE calendars SET gcal_watch_error_count = 0;')
    op.alter_column('calendars', 'gcal_watch_error_count', nullable=False)
    op.add_column('calendars', sa.Column('gcal_watch_last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendars', 'gcal_watch_last_error')
    op.drop_column('calendars', 'gcal_watch_error_count')
    # ### end Alembic commands ###
