"""Add gcal_response_state to attendances.

Revision ID: d726d6b9eaf6
Revises: 64cc31e5afba
Create Date: 2023-02-18 15:31:04.732805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd726d6b9eaf6'
down_revision = '64cc31e5afba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('gcal_response_state', sa.Integer(), nullable=True))
    op.execute('UPDATE attendances SET gcal_response_state = 0;')
    op.alter_column('attendances', 'gcal_response_state', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'gcal_response_state')
    # ### end Alembic commands ###
