"""Add support for all-day fixed events.

Revision ID: df6728bf3d0e
Revises: 7e8d91b94944
Create Date: 2022-04-26 11:28:11.494126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df6728bf3d0e'
down_revision = '7e8d91b94944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fixed_events', 'start_at', new_column_name='start_dt')
    op.alter_column('fixed_events', 'end_at', new_column_name='end_dt')
    op.add_column('fixed_events', sa.Column('all_day', sa.Boolean(), nullable=True))
    op.execute('UPDATE fixed_events SET all_day = false')
    op.alter_column('fixed_events', 'all_day', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixed_events', 'all_day')
    op.alter_column('fixed_events', 'start_dt', new_column_name='start_at')
    op.alter_column('fixed_events', 'end_dt', new_column_name='end_at')
    # ### end Alembic commands ###
