"""Add is_removed to users.

Revision ID: f9ca56593b8b
Revises: c6e96448900f
Create Date: 2023-09-22 14:54:17.163593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ca56593b8b'
down_revision = 'c6e96448900f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_removed', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET is_removed = false;')
    op.alter_column('users', 'is_removed', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_removed')
    # ### end Alembic commands ###
