"""Add final flag to events.

Revision ID: fc221bfe41a7
Revises: 3901456fb707
Create Date: 2022-09-09 17:54:44.639965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc221bfe41a7'
down_revision = '3901456fb707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('final', sa.Boolean(), nullable=True))
    op.execute('UPDATE events SET final = false;')
    op.alter_column('events', 'final', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'final')
    # ### end Alembic commands ###
